### PR TITLE
Use crates that generate the c bindings

### PR DESCRIPTION
**Pull request by ccouzens**
This avoids having to do the bindings a 2nd time in this project.

### CODE REVIEW

**Comment by houqp** [comment]
Thanks for the suggestion, I will need to test couple things myself first to make sure those crates are not causing any regression :)

I have the current setup so that cargo is not running bindgen on every build, which is very slow. I also had to go with the whitelisting approach to get rid of unnecessary symbols from libc.

**Comment by ccouzens** [comment]
> which is very slow

Leptonica-sys is still slow to build, but it doesn't need to be built very often

**Comment by houqp** [comment]
Are you able to build your branch? I just gave it a try and I am not able to build it due to tesseract-sys requiring a version of bindgen that doesn't exist.

**Comment by ccouzens** [comment]
It was working for me.
Then I deleted `Cargo.lock` and ran `cargo clean; cargo test`.
Now I get the same problem.

It looks like https://crates.io/crates/bindgen/0.49.3 has been yanked.

I'll relax the dependencies to be `bindgen = "0.50"`  tomorrow.

Thanks for finding the issue.

**Comment by ccouzens** [comment]
I didn't wait until tomorrow.

Relaxing the dependencies to be `bindgen = "0.50"` seems to have worked. Can you try again?

**Comment by houqp** [comment]
Thanks for the PR and sorry for the late reply :D

**Pull request merged**
