### PR TITLE
Fix typo in lib.rs

### PR DESCRIPTION
**Pull request by kvnxiao**
fix typo "safty" -> "safety"

### CODE REVIEW

**Comment by kvnxiao** [comment]
@ccouzens I would recommend removing the CircleCI integration with this repository, to prevent all main branch commits from showing up with a red X.

**Comment by ccouzens** [comment]
> @ccouzens I would recommend removing the CircleCI integration with this repository, to prevent all main branch commits from showing up with a red X.

That's one for @houqp. I don't have admin on circle ci

Screenshot_20220816-234333

(We switched to GitHub actions and deleted the circle ci plan from the code)

**Review by ccouzens — APPROVED** [review]

**Comment by ccouzens** [comment]
https://app.circleci.com/settings/project/github/houqp/leptess

**Comment by houqp** [comment]
done, i have disabled it in circleci :)

**Pull request merged**
