### PR TITLE
get_alto_text, get_tsv_text, get_lstm_box_text and get_word_str_box_text

### PR DESCRIPTION
**Pull request by Gearme**
I've implemented get_alto_text, get_tsv_text, get_lstm_box_text and get_word_str_box_text, they work pretty much like get_hocr_text.
Also implemented tests for them, adding regex to dev-dependencies for testing of output formats.

### CODE REVIEW

**Comment by ccouzens** [comment]
Thank you for your contribution Gearme.

Looks good to me, and I'm happy to merge in principle.

I'm looking into the [CI failure](https://app.circleci.com/pipelines/github/houqp/leptess/106/workflows/36c93b68-b5dc-453e-afd5-b9ae5fb55212/jobs/131). I suspect the version of tesseract used in the ci is too old to have the 4 functions in the c API (eg TessBaseAPIGetAltoText).

**Comment by ccouzens** [comment]
@Gearme , I hope to get https://github.com/houqp/leptess/pull/30 merged to fix your CI issue.
Once that's merged, I'll look at getting this merged.

**Comment by ccouzens** [comment]
Hi @Gearme , I've merged #30. When you have a moment could you please either merge with the master branch or rebase against it.

If you need help, I may be able to do it for you.

**Comment by Gearme** [comment]
I apologize for my tardiness - the changes have been merged now.

One side note: Locally, I've bumped the dependencies to leptonica-sys and tesseract-sys to their latest and they work fine. Didn't inlude them in this merge request though, since they're not required.

**Review by ccouzens — APPROVED** [review]
Looks good to me :+1:

**Comment by ccouzens** [comment]
All merged and package @Gearme 

0.11.0 should be good to go for you
https://crates.io/crates/leptess/0.11.0

Thanks for the PR :)

**Comment by houqp** [comment]
Thanks @Gearme for the new methods and tests indeed!

**Pull request merged**
